"""add_password_hash_to_users

Revision ID: 032605f9a7a7
Revises: fbb9482bc9a9
Create Date: 2026-06-13 21:51:48.811522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '032605f9a7a7'
down_revision: Union[str, None] = 'fbb9482bc9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
