"""amplia metodo_entrega_triat a varchar 30

Revision ID: 09134b164755
Revises: 8753bfc07fa4
Create Date: 2026-07-16 19:30:52.584435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09134b164755'
down_revision: Union[str, None] = '8753bfc07fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peticiones_cliente', 'metodo_entrega_triat',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('peticiones_cliente', 'metodo_entrega_triat',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
