"""add_caja_movimientos

Revision ID: 156f8ba1f59f
Revises: 46573dba63c9
Create Date: 2026-06-11 13:27:28.262337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '156f8ba1f59f'
down_revision: Union[str, None] = '46573dba63c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caja_movimientos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', name='tipo_movimiento'), nullable=False),
    sa.Column('concepto', sa.String(length=300), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['caja_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caja_movimientos_fecha'), 'caja_movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_caja_movimientos_session_id'), 'caja_movimientos', ['session_id'], unique=False)
    op.create_index(op.f('ix_caja_movimientos_tipo'), 'caja_movimientos', ['tipo'], unique=False)
    op.add_column('caja_sessions', sa.Column('total_entradas', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('caja_sessions', sa.Column('total_salidas', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caja_sessions', 'total_salidas')
    op.drop_column('caja_sessions', 'total_entradas')
    op.drop_index(op.f('ix_caja_movimientos_tipo'), table_name='caja_movimientos')
    op.drop_index(op.f('ix_caja_movimientos_session_id'), table_name='caja_movimientos')
    op.drop_index(op.f('ix_caja_movimientos_fecha'), table_name='caja_movimientos')
    op.drop_table('caja_movimientos')
    # ### end Alembic commands ###
