"""add_idioma_to_auth_tokens_and_orders

Revision ID: 1794a357e791
Revises: ac1b10ee299c
Create Date: 2026-07-29 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1794a357e791'
down_revision: Union[str, None] = 'ac1b10ee299c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('idioma', sa.String(length=5), nullable=True))
    op.add_column('orders', sa.Column('idioma', sa.String(length=5), server_default='ca', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'idioma')
    op.drop_column('auth_tokens', 'idioma')
    # ### end Alembic commands ###
