"""platform_admin_and_email_from

Revision ID: 241bdc35acbf
Revises: 9ee2df1716bf
Create Date: 2026-08-06 22:08:25.564715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '241bdc35acbf'
down_revision: Union[str, None] = '9ee2df1716bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_activo'), 'platform_admins', ['activo'], unique=False)
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.add_column('configuracio_botiga', sa.Column('email_from', sa.String(length=300), nullable=True))
    # NOTA: autogenerate también proponía un alter_column sobre
    # configuracio_botiga.id quitándole el server_default de Identity — es
    # ruido cosmético (el modelo declara autoincrement=True sin un objeto
    # Identity() explícito, ver nota en la migración 9ee2df1716bf) que
    # aplicado tal cual DESHARÍA el arreglo de la Fase 1 que le dio
    # secuencia real a esa columna. Descartado a propósito, no por omisión.
    # Igual con el drop_constraint de cobraments_subscripcio_ds_order_key:
    # drift preexistente ajeno a este cambio (ver nota equivalente en la
    # migración de Fase 1), no se toca aquí.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracio_botiga', 'email_from')
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_index(op.f('ix_platform_admins_activo'), table_name='platform_admins')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
