"""afegeix newsletter campaigns i sends

Revision ID: 2c690b8e9247
Revises: 9c1d4f2a6b31
Create Date: 2026-07-03 10:32:17.135129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c690b8e9247'
down_revision: Union[str, None] = '9c1d4f2a6b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assumpte', sa.String(length=200), nullable=False),
    sa.Column('contingut_html', sa.Text(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('estat', sa.Enum('esborrany', 'enviant', 'enviada', name='newsletter_campaign_status'), nullable=False),
    sa.Column('creat_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviament_iniciat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviament_acabat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creat_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_campaigns_estat'), 'newsletter_campaigns', ['estat'], unique=False)
    op.create_table('newsletter_sends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('estat', sa.Enum('pendent', 'enviat', 'error', name='newsletter_send_status'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('unsubscribe_token_hash', sa.String(length=64), nullable=False),
    sa.Column('enviat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['newsletter_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id'),
    sa.UniqueConstraint('unsubscribe_token_hash')
    )
    op.create_index(op.f('ix_newsletter_sends_estat'), 'newsletter_sends', ['estat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_sends_estat'), table_name='newsletter_sends')
    op.drop_table('newsletter_sends')
    op.drop_index(op.f('ix_newsletter_campaigns_estat'), table_name='newsletter_campaigns')
    op.drop_table('newsletter_campaigns')
    # ### end Alembic commands ###
