"""afegeix peticiones_cliente

Revision ID: 613cb77f674d
Revises: 778e334df27a
Create Date: 2026-07-15 19:43:33.223517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '613cb77f674d'
down_revision: Union[str, None] = '778e334df27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peticiones_cliente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('artista_lliure', sa.String(length=300), nullable=True),
    sa.Column('titulo_lliure', sa.String(length=300), nullable=True),
    sa.Column('notas_cliente', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendent', 'pendent_acceptacio', 'acceptada', 'rebutjada', 'en_tramit', 'reservada', 'recollida', 'caducada', 'cancelada', name='estado_peticion_cliente'), nullable=False),
    sa.Column('precio_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metodo_entrega_triat', sa.String(length=20), nullable=True),
    sa.Column('solicitud_compra_linea_id', sa.Uuid(), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('notas_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_compra_linea_id'], ['solicitud_compra_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peticiones_cliente_estado'), 'peticiones_cliente', ['estado'], unique=False)
    op.create_index(op.f('ix_peticiones_cliente_item_id'), 'peticiones_cliente', ['item_id'], unique=False)
    op.create_index(op.f('ix_peticiones_cliente_order_id'), 'peticiones_cliente', ['order_id'], unique=False)
    op.create_index(op.f('ix_peticiones_cliente_release_id'), 'peticiones_cliente', ['release_id'], unique=False)
    op.create_index(op.f('ix_peticiones_cliente_solicitud_compra_linea_id'), 'peticiones_cliente', ['solicitud_compra_linea_id'], unique=False)
    op.create_index(op.f('ix_peticiones_cliente_user_id'), 'peticiones_cliente', ['user_id'], unique=False)
    op.add_column('items', sa.Column('reserved_for_peticion_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_items_reserved_for_peticion_id', 'items', 'peticiones_cliente',
        ['reserved_for_peticion_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_items_reserved_for_peticion_id', 'items', type_='foreignkey')
    op.drop_column('items', 'reserved_for_peticion_id')
    op.drop_index(op.f('ix_peticiones_cliente_user_id'), table_name='peticiones_cliente')
    op.drop_index(op.f('ix_peticiones_cliente_solicitud_compra_linea_id'), table_name='peticiones_cliente')
    op.drop_index(op.f('ix_peticiones_cliente_release_id'), table_name='peticiones_cliente')
    op.drop_index(op.f('ix_peticiones_cliente_order_id'), table_name='peticiones_cliente')
    op.drop_index(op.f('ix_peticiones_cliente_item_id'), table_name='peticiones_cliente')
    op.drop_index(op.f('ix_peticiones_cliente_estado'), table_name='peticiones_cliente')
    op.drop_table('peticiones_cliente')
    # ### end Alembic commands ###
