"""add_tracking_to_orders

Revision ID: 63370ba828f3
Revises: 032605f9a7a7
Create Date: 2026-06-16 20:11:49.571765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '63370ba828f3'
down_revision: Union[str, None] = '032605f9a7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('numero_seguiment', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('transportista', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'transportista')
    op.drop_column('orders', 'numero_seguiment')
    # ### end Alembic commands ###
