"""afegeix historial_compres

Revision ID: 6cd48785a862
Revises: 754348061bb9
Create Date: 2026-07-15 10:47:31.798063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6cd48785a862'
down_revision: Union[str, None] = '754348061bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_compres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('artista', sa.String(length=300), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('sello', sa.String(length=500), nullable=True),
    sa.Column('formato', sa.String(length=120), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_coste', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_compres_artista'), 'historial_compres', ['artista'], unique=False)
    op.create_index(op.f('ix_historial_compres_fecha'), 'historial_compres', ['fecha'], unique=False)
    op.create_index(op.f('ix_historial_compres_proveedor_id'), 'historial_compres', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_historial_compres_release_id'), 'historial_compres', ['release_id'], unique=False)
    op.create_index(op.f('ix_historial_compres_sello'), 'historial_compres', ['sello'], unique=False)
    op.create_index(op.f('ix_historial_compres_titulo'), 'historial_compres', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_compres_titulo'), table_name='historial_compres')
    op.drop_index(op.f('ix_historial_compres_sello'), table_name='historial_compres')
    op.drop_index(op.f('ix_historial_compres_release_id'), table_name='historial_compres')
    op.drop_index(op.f('ix_historial_compres_proveedor_id'), table_name='historial_compres')
    op.drop_index(op.f('ix_historial_compres_fecha'), table_name='historial_compres')
    op.drop_index(op.f('ix_historial_compres_artista'), table_name='historial_compres')
    op.drop_table('historial_compres')
    # ### end Alembic commands ###
