"""trams_enviament, pes_g, coste_envio i camps correos

Revision ID: 6de512e146c2
Revises: b3c4d5e6f7a8
Create Date: 2026-07-23 12:28:28.441364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6de512e146c2'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trams_enviament',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pes_maxim_g', sa.Integer(), nullable=False),
    sa.Column('preu', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('actiu', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trams_enviament_actiu'), 'trams_enviament', ['actiu'], unique=False)
    # NOTA: no toquem 'etiquetes_slug_key' aquí — l'autogenerate el detecta
    # com a drift preexistent no relacionat amb aquest canvi; fora d'abast.
    op.add_column('orders', sa.Column('coste_envio', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('correos_shipment_id', sa.String(length=80), nullable=True))
    op.add_column('orders', sa.Column('correos_label_status', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('correos_raw_response', sa.JSON(), nullable=True))
    op.add_column('releases', sa.Column('pes_g', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'pes_g')
    op.drop_column('orders', 'correos_raw_response')
    op.drop_column('orders', 'correos_label_status')
    op.drop_column('orders', 'correos_shipment_id')
    op.drop_column('orders', 'coste_envio')
    op.drop_index(op.f('ix_trams_enviament_actiu'), table_name='trams_enviament')
    op.drop_table('trams_enviament')
    # ### end Alembic commands ###
