"""add_translations

Revision ID: 702f4d275cd9
Revises: 3051426b0eaf
Create Date: 2026-06-11 09:45:18.159065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '702f4d275cd9'
down_revision: Union[str, None] = '3051426b0eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'lang')
    )
    op.create_index(op.f('ix_translations_key'), 'translations', ['key'], unique=False)
    op.create_index(op.f('ix_translations_lang'), 'translations', ['lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_lang'), table_name='translations')
    op.drop_index(op.f('ix_translations_key'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
