"""afegeix pes_format per calcular pes per defecte segons format

Revision ID: 707539b40f03
Revises: 6de512e146c2
Create Date: 2026-07-23 13:50:10.570516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '707539b40f03'
down_revision: Union[str, None] = '6de512e146c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


pes_format = sa.table(
    'pes_format',
    sa.column('formato', sa.String),
    sa.column('pes_g', sa.Integer),
)

# Pesos inicials orientatius (grams) perquè el càlcul d'enviament funcioni
# sense haver de configurar res d'entrada; editables des de l'admin després.
PESOS_INICIALS = [
    {'formato': 'LP', 'pes_g': 350},
    {'formato': 'EP', 'pes_g': 200},
    {'formato': '7"', 'pes_g': 120},
    {'formato': '12"', 'pes_g': 250},
    {'formato': 'CD', 'pes_g': 100},
    {'formato': 'Cassette', 'pes_g': 80},
    {'formato': 'Altre', 'pes_g': 300},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pes_format',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formato', sa.String(length=120), nullable=False),
    sa.Column('pes_g', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formato')
    )
    # NOTA: no toquem 'etiquetes_slug_key' aquí — l'autogenerate el detecta
    # com a drift preexistent no relacionat amb aquest canvi; fora d'abast.
    # ### end Alembic commands ###
    op.bulk_insert(pes_format, PESOS_INICIALS)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pes_format')
    # ### end Alembic commands ###
