"""afegeix solicitudes_compra

Revision ID: 778e334df27a
Revises: 6cd48785a862
Create Date: 2026-07-15 10:57:43.188420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '778e334df27a'
down_revision: Union[str, None] = '6cd48785a862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_compra',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('oberta', 'resolta', 'cancelada', name='estado_solicitud'), nullable=False),
    sa.Column('origen', sa.Enum('manual', 'refill_stock', name='origen_solicitud'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_compra_estado'), 'solicitudes_compra', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_compra_origen'), 'solicitudes_compra', ['origen'], unique=False)
    op.create_index(op.f('ix_solicitudes_compra_user_id'), 'solicitudes_compra', ['user_id'], unique=False)
    op.create_table('solicitud_compra_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('solicitud_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('artista', sa.String(length=300), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('sello', sa.String(length=500), nullable=True),
    sa.Column('formato', sa.String(length=120), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('proveedor_sugerido_id', sa.Uuid(), nullable=True),
    sa.Column('comanda_linea_id', sa.Uuid(), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comanda_linea_id'], ['comanda_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_sugerido_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_compra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_compra_items_comanda_linea_id'), 'solicitud_compra_items', ['comanda_linea_id'], unique=False)
    op.create_index(op.f('ix_solicitud_compra_items_proveedor_sugerido_id'), 'solicitud_compra_items', ['proveedor_sugerido_id'], unique=False)
    op.create_index(op.f('ix_solicitud_compra_items_release_id'), 'solicitud_compra_items', ['release_id'], unique=False)
    op.create_index(op.f('ix_solicitud_compra_items_solicitud_id'), 'solicitud_compra_items', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitud_compra_items_solicitud_id'), table_name='solicitud_compra_items')
    op.drop_index(op.f('ix_solicitud_compra_items_release_id'), table_name='solicitud_compra_items')
    op.drop_index(op.f('ix_solicitud_compra_items_proveedor_sugerido_id'), table_name='solicitud_compra_items')
    op.drop_index(op.f('ix_solicitud_compra_items_comanda_linea_id'), table_name='solicitud_compra_items')
    op.drop_table('solicitud_compra_items')
    op.drop_index(op.f('ix_solicitudes_compra_user_id'), table_name='solicitudes_compra')
    op.drop_index(op.f('ix_solicitudes_compra_origen'), table_name='solicitudes_compra')
    op.drop_index(op.f('ix_solicitudes_compra_estado'), table_name='solicitudes_compra')
    op.drop_table('solicitudes_compra')
    # ### end Alembic commands ###
