"""permet order_items sense item_id per a peticions pagades per endavant

Revision ID: 8753bfc07fa4
Revises: 92196d22bb66
Create Date: 2026-07-16 19:15:38.342002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8753bfc07fa4'
down_revision: Union[str, None] = '92196d22bb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('release_id', sa.Uuid(), nullable=True))
    op.alter_column('order_items', 'item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_order_items_release_id'), 'order_items', ['release_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'releases', ['release_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_release_id'), table_name='order_items')
    op.alter_column('order_items', 'item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('order_items', 'release_id')
    # ### end Alembic commands ###
