"""add payments and order cart_id

Revision ID: 8842d1e29d14
Revises: f3a1c9d24e88
Create Date: 2026-07-14 18:45:25.383309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8842d1e29d14'
down_revision: Union[str, None] = 'f3a1c9d24e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('proveedor', sa.String(length=20), nullable=False),
    sa.Column('ds_order', sa.String(length=12), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('estado', sa.Enum('creado', 'autorizado', 'denegado', 'error', name='payment_status'), nullable=False),
    sa.Column('ds_response_code', sa.String(length=10), nullable=True),
    sa.Column('ds_authorisation_code', sa.String(length=20), nullable=True),
    sa.Column('raw_notification', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_ds_order'), 'payments', ['ds_order'], unique=True)
    op.create_index(op.f('ix_payments_estado'), 'payments', ['estado'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('cart_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('orders_cart_id_fkey', 'orders', 'carts', ['cart_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_cart_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'cart_id')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_estado'), table_name='payments')
    op.drop_index(op.f('ix_payments_ds_order'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
