"""afegeix item_resuelto_id a solicitud_compra_items

Revision ID: 92196d22bb66
Revises: bbf220956083
Create Date: 2026-07-16 15:11:39.778536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92196d22bb66'
down_revision: Union[str, None] = 'bbf220956083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud_compra_items', sa.Column('item_resuelto_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_solicitud_compra_items_item_resuelto_id'), 'solicitud_compra_items', ['item_resuelto_id'], unique=False)
    op.create_foreign_key(None, 'solicitud_compra_items', 'items', ['item_resuelto_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitud_compra_items', type_='foreignkey')
    op.drop_index(op.f('ix_solicitud_compra_items_item_resuelto_id'), table_name='solicitud_compra_items')
    op.drop_column('solicitud_compra_items', 'item_resuelto_id')
    # ### end Alembic commands ###
