"""add_user_links_and_user_fields

Revision ID: 991782a64e63
Revises: 156f8ba1f59f
Create Date: 2026-06-11 14:03:48.386638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '991782a64e63'
down_revision: Union[str, None] = '156f8ba1f59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_compras_user_id'), 'compras', ['user_id'], unique=False)
    op.create_foreign_key(None, 'compras', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('telefon', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('notas_internes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_activo'), 'users', ['activo'], unique=False)
    op.add_column('ventas_externas', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ventas_externas_user_id'), 'ventas_externas', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ventas_externas', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas_externas', type_='foreignkey')
    op.drop_index(op.f('ix_ventas_externas_user_id'), table_name='ventas_externas')
    op.drop_column('ventas_externas', 'user_id')
    op.drop_index(op.f('ix_users_activo'), table_name='users')
    op.drop_column('users', 'notas_internes')
    op.drop_column('users', 'activo')
    op.drop_column('users', 'telefon')
    op.drop_constraint(None, 'compras', type_='foreignkey')
    op.drop_index(op.f('ix_compras_user_id'), table_name='compras')
    op.drop_column('compras', 'user_id')
    # ### end Alembic commands ###
