"""articles_manuals_al_tpv

Revision ID: aa37c7aded56
Revises: 1794a357e791
Create Date: 2026-07-30 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa37c7aded56'
down_revision: Union[str, None] = '1794a357e791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas_externas', 'item_id', existing_type=sa.UUID(), nullable=True)
    op.add_column('ventas_externas', sa.Column('descripcion', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas_externas', 'descripcion')
    op.alter_column('ventas_externas', 'item_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
