"""initial_schema

Revision ID: ab4340a7ea5a
Revises: 
Create Date: 2026-06-11 08:36:52.026075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab4340a7ea5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_tokens_email'), 'auth_tokens', ['email'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=400), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lugar', sa.String(length=300), nullable=False),
    sa.Column('link', sa.String(length=800), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_fecha'), 'events', ['fecha'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('titulo', sa.String(length=400), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('publicado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legacy_blogger_url', sa.String(length=800), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_publicado_at'), 'posts', ['publicado_at'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_table('proveedores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('contacto', sa.String(length=300), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=True)
    op.create_table('releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artista', sa.String(length=300), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('sello', sa.String(length=500), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('formato', sa.String(length=120), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=800), nullable=True),
    sa.Column('discogs_release_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_artista'), 'releases', ['artista'], unique=False)
    op.create_index(op.f('ix_releases_discogs_release_id'), 'releases', ['discogs_release_id'], unique=False)
    op.create_index(op.f('ix_releases_formato'), 'releases', ['formato'], unique=False)
    op.create_index(op.f('ix_releases_genero'), 'releases', ['genero'], unique=False)
    op.create_index(op.f('ix_releases_titulo'), 'releases', ['titulo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('consent_newsletter', sa.Boolean(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_destinatario', sa.String(length=200), nullable=False),
    sa.Column('linea1', sa.String(length=300), nullable=False),
    sa.Column('linea2', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('cp', sa.String(length=20), nullable=False),
    sa.Column('provincia', sa.String(length=120), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('predeterminada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('compras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('proveedor', 'particular', name='tipo_compra'), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=True),
    sa.Column('nombre_particular', sa.String(length=300), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('num_factura', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_fecha'), 'compras', ['fecha'], unique=False)
    op.create_index(op.f('ix_compras_proveedor_id'), 'compras', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_compras_tipo'), 'compras', ['tipo'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_index(op.f('ix_identities_user_id'), 'identities', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email_contacto', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('pendiente_pago', 'pagado', 'enviado', 'entregado', 'cancelado', name='order_status'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_envio', sa.String(length=40), nullable=False),
    sa.Column('direccion_envio', sa.JSON(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('codi_discogs', sa.BigInteger(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_disco', sa.String(length=60), nullable=True),
    sa.Column('estado_funda', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('disponible', 'reservado', 'vendido', 'retirado', name='item_status'), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_entrada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('coste_adquisicion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('compra_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codi_discogs')
    )
    op.create_index(op.f('ix_items_compra_id'), 'items', ['compra_id'], unique=False)
    op.create_index(op.f('ix_items_release_id'), 'items', ['release_id'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'item_id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_item_id'), 'cart_items', ['item_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('ventas_externas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('canal', sa.Enum('mostrador', 'discogs', 'otro', name='canal_venta'), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discogs_sale_id', sa.BigInteger(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_ventas_externas_canal'), 'ventas_externas', ['canal'], unique=False)
    op.create_index(op.f('ix_ventas_externas_fecha'), 'ventas_externas', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_externas_fecha'), table_name='ventas_externas')
    op.drop_index(op.f('ix_ventas_externas_canal'), table_name='ventas_externas')
    op.drop_table('ventas_externas')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cart_items_item_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_release_id'), table_name='items')
    op.drop_index(op.f('ix_items_compra_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_identities_user_id'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_compras_tipo'), table_name='compras')
    op.drop_index(op.f('ix_compras_proveedor_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_fecha'), table_name='compras')
    op.drop_table('compras')
    op.drop_table('carts')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_releases_titulo'), table_name='releases')
    op.drop_index(op.f('ix_releases_genero'), table_name='releases')
    op.drop_index(op.f('ix_releases_formato'), table_name='releases')
    op.drop_index(op.f('ix_releases_discogs_release_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_artista'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index(op.f('ix_posts_publicado_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_events_fecha'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_auth_tokens_email'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
