"""add metodo_pago to orders

Revision ID: c4024b25f384
Revises: 8842d1e29d14
Create Date: 2026-07-14 18:58:32.380180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4024b25f384'
down_revision: Union[str, None] = '8842d1e29d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('metodo_pago', sa.String(length=20), server_default='redsys', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'metodo_pago')
    # ### end Alembic commands ###
