"""add_nombre_cliente_and_caja_sessions

Revision ID: cf929c5314c0
Revises: ddf6d8260a07
Create Date: 2026-06-11 13:01:25.339660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cf929c5314c0'
down_revision: Union[str, None] = 'ddf6d8260a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caja_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fondo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_ventas_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conteo_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caja_sessions_fecha_apertura'), 'caja_sessions', ['fecha_apertura'], unique=False)
    op.add_column('ventas_externas', sa.Column('nombre_cliente', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas_externas', 'nombre_cliente')
    op.drop_index(op.f('ix_caja_sessions_fecha_apertura'), table_name='caja_sessions')
    op.drop_table('caja_sessions')
    # ### end Alembic commands ###
