"""add_devolucions

Revision ID: ddf6d8260a07
Revises: 702f4d275cd9
Create Date: 2026-06-11 10:27:54.255383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ddf6d8260a07'
down_revision: Union[str, None] = '702f4d275cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolucions_compra',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('compra_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devolucions_compra_compra_id'), 'devolucions_compra', ['compra_id'], unique=False)
    op.create_index(op.f('ix_devolucions_compra_fecha'), 'devolucions_compra', ['fecha'], unique=False)
    op.create_index(op.f('ix_devolucions_compra_item_id'), 'devolucions_compra', ['item_id'], unique=False)
    op.create_table('devolucions_venta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('venta_externa_id', sa.Uuid(), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('destino_item', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_externa_id'], ['ventas_externas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devolucions_venta_fecha'), 'devolucions_venta', ['fecha'], unique=False)
    op.create_index(op.f('ix_devolucions_venta_item_id'), 'devolucions_venta', ['item_id'], unique=False)
    op.create_index(op.f('ix_devolucions_venta_order_item_id'), 'devolucions_venta', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_devolucions_venta_venta_externa_id'), 'devolucions_venta', ['venta_externa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devolucions_venta_venta_externa_id'), table_name='devolucions_venta')
    op.drop_index(op.f('ix_devolucions_venta_order_item_id'), table_name='devolucions_venta')
    op.drop_index(op.f('ix_devolucions_venta_item_id'), table_name='devolucions_venta')
    op.drop_index(op.f('ix_devolucions_venta_fecha'), table_name='devolucions_venta')
    op.drop_table('devolucions_venta')
    op.drop_index(op.f('ix_devolucions_compra_item_id'), table_name='devolucions_compra')
    op.drop_index(op.f('ix_devolucions_compra_fecha'), table_name='devolucions_compra')
    op.drop_index(op.f('ix_devolucions_compra_compra_id'), table_name='devolucions_compra')
    op.drop_table('devolucions_compra')
    # ### end Alembic commands ###
