"""add_origen_discogs_to_orders

Revision ID: ed0cb3ae47e4
Revises: 63370ba828f3
Create Date: 2026-06-16 20:43:11.419014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed0cb3ae47e4'
down_revision: Union[str, None] = '63370ba828f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    order_origen = sa.Enum('web', 'discogs', name='order_origen')
    order_origen.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('origen', sa.Enum('web', 'discogs', name='order_origen'), server_default='web', nullable=False))
    op.add_column('orders', sa.Column('discogs_order_id', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('discogs_buyer', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_orders_discogs_order_id'), 'orders', ['discogs_order_id'], unique=True)
    op.create_index(op.f('ix_orders_origen'), 'orders', ['origen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_origen'), table_name='orders')
    op.drop_index(op.f('ix_orders_discogs_order_id'), table_name='orders')
    op.drop_column('orders', 'discogs_buyer')
    op.drop_column('orders', 'discogs_order_id')
    op.drop_column('orders', 'origen')
    sa.Enum(name='order_origen').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
